/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/todos": {
    /** Get all todos */
    get: {
      responses: {
        /** @description A list of todos */
        200: {
          content: {
            "application/json": components["schemas"]["Todo"][];
          };
        };
      };
    };
    /** Create a new todo */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Todo"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Todo: {
      id?: number;
      title?: string;
      done?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
