generate:
	oapi-codegen -package=gen --generate=chi-server ../schema/openai.yaml > generated/server/opanai.go
	oapi-codegen -package=gen --generate=types ../schema/openai.yaml > generated/models/opanai.go
